# .github/workflows/test-publish.yml
name: Publish to TestPyPI

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build-and-publish-test:
    name: Build and Publish to TestPyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev] # Install semantic-release and build tools

      - name: Build package
        run: python -m build

      - name: Verify built distributions (Optional but Recommended)
        run: |
          ls -l dist/
          twine check dist/*

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.PYPI_TEST }}
